# Generated by Django 2.1.2 on 2019-01-02 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('cage_num', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cage',
            },
        ),
        migrations.CreateModel(
            name='CreditOrder',
            fields=[
                ('order_num', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'credit_order',
            },
        ),
        migrations.CreateModel(
            name='EmpInfo',
            fields=[
                ('emp_num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_time', models.IntegerField(blank=True, null=True)),
                ('salary_basic', models.IntegerField(blank=True, null=True)),
                ('last_paid_time', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emp_info',
            },
        ),
        migrations.CreateModel(
            name='FosterOrder',
            fields=[
                ('foster_num', models.IntegerField(primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('cage_num', models.ForeignKey(blank=True, db_column='cage_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.Cage')),
            ],
            options={
                'db_table': 'foster_order',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product_num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('min', models.IntegerField(blank=True, null=True)),
                ('max', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('stock_price', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_num', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('point', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='MemberPet',
            fields=[
                ('pet_num', models.IntegerField(primary_key=True, serialize=False)),
                ('pet_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=225, null=True)),
                ('mem_num', models.ForeignKey(blank=True, db_column='mem_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.Member')),
            ],
            options={
                'db_table': 'member-pet',
            },
        ),
        migrations.CreateModel(
            name='SalaryOrder',
            fields=[
                ('salary_order_num', models.IntegerField(primary_key=True, serialize=False)),
                ('last_paid_time', models.DateTimeField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('emp_num', models.ForeignKey(blank=True, db_column='emp_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.EmpInfo')),
            ],
            options={
                'db_table': 'salary_order',
            },
        ),
        migrations.CreateModel(
            name='ServiceReservation',
            fields=[
                ('res_num', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('final_price', models.IntegerField(blank=True, null=True)),
                ('emp_num', models.ForeignKey(blank=True, db_column='emp_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.EmpInfo')),
                ('mem_num', models.ForeignKey(blank=True, db_column='mem_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.Member')),
                ('pet_num', models.ForeignKey(blank=True, db_column='pet_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.MemberPet')),
            ],
            options={
                'db_table': 'service_reservation',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('service_num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_type',
            },
        ),
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('stock_num', models.AutoField(primary_key=True, serialize=False)),
                ('product_num', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('final_price', models.IntegerField(blank=True, null=True)),
                ('time', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_order',
            },
        ),
        migrations.AddField(
            model_name='servicereservation',
            name='service_num',
            field=models.ForeignKey(blank=True, db_column='service_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.ServiceType'),
        ),
        migrations.AddField(
            model_name='fosterorder',
            name='pet_num',
            field=models.ForeignKey(blank=True, db_column='pet_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.MemberPet'),
        ),
        migrations.AddField(
            model_name='fosterorder',
            name='product_num',
            field=models.ForeignKey(blank=True, db_column='product_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.Inventory'),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='service_num',
            field=models.ForeignKey(blank=True, db_column='service_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.ServiceType'),
        ),
        migrations.AddField(
            model_name='creditorder',
            name='mem_num',
            field=models.ForeignKey(blank=True, db_column='mem_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.Member'),
        ),
        migrations.AddField(
            model_name='creditorder',
            name='product_num',
            field=models.ForeignKey(blank=True, db_column='product_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.Inventory'),
        ),
    ]
